### ISSUE TITLE
Convert VDB SOP: add a Level Of Detail parameter

### ISSUE THREAD

**Issue by jdiversen** [dreamworksanimation/openvdb#10]
It would be great to be able to convert to Polygons at a different (lower) rate than the VDB resolution without using a VDB Resample SOP to do it. This would be convenient and more efficient, if possible.

Thanks,
Jason

**Comment by OpenVDB-DevTeam** [comment]
The polygonal mesh extraction has a surface adaptivity threshold.

**Comment by mojovski** [comment]
How can I interpret the threshold? Is there a paper or something similar, which explains the concept?
