### ISSUE TITLE
Point data

### ISSUE THREAD

**Issue by nyue** [dreamworksanimation/openvdb#108]
Hi,

  Having created some OpenVDB 4.0 point data and writing them out to disk, I don't see them when I view them in vdb_view

  I tried using Houdini "OpenVDB Read" SOP node, still without success.

  What is the work flow utilizing point data in OpenVDB 4.0 ?

Cheers

**Comment by danrbailey** [comment]
Hi @nyue, there's no support for VDB Points in vdb_view yet unfortunately.

The OpenVDB Read SOP should work fine. although note that by default it will be loading the points using delayed loading, so you should see the out-of-core bounding box display only - try disabling delayed loading on the Read SOP to load the points into the viewport. 

Another simple test I can suggest is to take some Houdini points, feed them into an OpenVDB Points Convert SOP using the default options on the node and it will convert them into a VDB points grid for you. MMB on the SOP to inspect the data.

**Comment by nyue** [comment]
Got it. Disabling the delayed loading, I can see the points in the view port.

Which example should I look into for best practice if I am writing pipeline tools (C++) that need to get the points information ? e.g. I may need to write some Procedural DSO for a renderer etc.

Cheers

**Comment by danrbailey** [comment]
Great. :)

We were a bit rushed to get VDB 4.0 out, so documentation and examples haven't yet been added to the repo. However, the best example is probably the TestPointConversion::testPointConversion unit test which does a round-trip conversion from linear point arrays -> a point data grid -> linear point arrays with a variety of different attributes and groups.

Other than that, I've just submitted a pull request with the VDB Points Mantra rendering procedural that might serve as a good demonstration:

https://github.com/dreamworksanimation/openvdb/pull/107

**Comment by nyue** [comment]
Thank you, I am looking forward to the Mantra procedural.
