### ISSUE TITLE
unsigned int vs. unsigned long long discrepancy

### ISSUE THREAD

**Issue by malaterre** [dreamworksanimation/openvdb#12]
The i386 build of openvdb failed with errors indicating that it was
trying to use templates specialized on unsigned int whereas it needed
variants specialized on unsigned long long:

  In file included from ./openvdb/tree/LeafNode.h:41:0,
                   from ./openvdb/tree/Tree.h:52,
                   from ./openvdb/Grid.h:43,
                   from ./openvdb/openvdb.h:39,
                   from viewer/RenderModules.h:34,
                   from viewer/RenderModules.cc:31:
  /usr/include/tbb/parallel_for.h: In instantiation of 'void tbb::interface6::internal::start_for<Range, Body, Partitioner>::run_body(Range&) [with Range = tbb::blocked_range<unsigned int>; Body = openvdb_viewer::PointGenerator<const openvdb::v1_2::tree::Tree<openvdb::v1_2::tree::RootNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::LeafNode<long long int, 3u>, 4u>, 5u> > > >; Partitioner = tbb::auto_partitioner]':
  /usr/include/tbb/partitioner.h:247:13:   required from 'void tbb::interface6::internal::partition_type_base<Partition>::execute(StartType&, Range&) [with StartType = tbb::interface6::internal::start_for<tbb::blocked_range<unsigned int>, openvdb_viewer::PointGenerator<const openvdb::v1_2::tree::Tree<openvdb::v1_2::tree::RootNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::LeafNode<long long int, 3u>, 4u>, 5u> > > >, tbb::auto_partitioner>; Range = tbb::blocked_range<unsigned int>; Partition = tbb::interface6::internal::auto_partition_type]'
  /usr/include/tbb/parallel_for.h:116:9:   required from 'tbb::task* tbb::interface6::internal::start_for<Range, Body, Partitioner>::execute() [with Range = tbb::blocked_range<unsigned int>; Body = openvdb_viewer::PointGenerator<const openvdb::v1_2::tree::Tree<openvdb::v1_2::tree::RootNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::InternalNode<openvdb::v1_2::tree::LeafNode<long long int, 3u>, 4u>, 5u> > > >; Partitioner = tbb::auto_partitioner]'
  viewer/RenderModules.cc:600:1:   required from here
  [...]

It's not clear what actually needs these specific instantiations, or
for that matter why they're not a problem elsewhere, as the only
requirer cited that isn't itself a template is the brace closing
RenderModules.cc's namespace openvdb_viewer { ... } construct.

ref:
http://bugs.debian.org/715427

**Comment by OpenVDB-DevTeam** [comment]
resolved using LeafManagerType::RangeType
