### ISSUE TITLE
Example code compilation fails.

### ISSUE THREAD

**Issue by norouzzadeh** [dreamworksanimation/openvdb#126]
I have compiled and installed the openvdb latest commit in Ubuntu 16.04 with boost 1.58 successfully.
During the compilation of any cookbook examples, i get the following error:

In function `openvdb::v4_0_1::math::AffineMap::postRotate(double, openvdb::v4_0_1::math::Axis) const':
/usr/local/include/openvdb/math/Maps.h:619: undefined reference to `openvdb::v4_0_1::math::simplify(std::shared_ptr<openvdb::v4_0_1::math::AffineMap>)'

The simplify function in OpenVDB library is defined as:
openvdb::v4_0_1::math::simplify(boost::shared_ptr<openvdb::v4_0_1::math::AffineMap>)

But in the Maps.h it is defined as
OPENVDB_API SharedPtr<MapBase> simplify(SharedPtr<AffineMap> affine);

where
template<typename T> using SharedPtr = std::shared_ptr<T>;

I think that, it shall be declared as boost::shared_ptr instead of std::shared_ptr.

**Comment by danrbailey** [comment]
Hi @norouzzadeh,

I believe the issue is that you're compiling the OpenVDB library with ABI=3 and codebook examples with ABI=4.

SharedPtr is actually defined as follows:

* ABI=3 boost::shared_ptr
* ABI=4 std::shared_ptr

Provided that you use the same ABI for both (the library and the binary), they should be compatible with each other.

**Comment by norouzzadeh** [comment]
Hi @danrbailey ,

That's right. Thanks a lot.

**Comment by MeghaS94** [comment]
I have installed the vdb 4.0.0 version with abi=3, when I compile the example code, I run into the similar error, `undefined reference to openvdb::v4_0_0::math::simplify(std::shared_ptr<openvdb::v4_0_0::math::AffineMap>)` . I am not sure how to set the ABI during compilation. Is it a flag that needs to be set during compilation or in the code somehow?
