### ISSUE TITLE
util/NodeMasks.h: B2 macro conflicting with other code

### ISSUE THREAD

**Issue by TrevorThomson** [dreamworksanimation/openvdb#129]
Hi,
I'm using OpenVDB and the Eigen library together and the B2 macro in openvdb/util/NodeMasks.h conflicts with an object in the Eigen library.  Would it be possibly for you to rename the B2, B4, B6 macros in such a way as to be unlikely to conflict with other code?  Or possibly not use #define at all?
Thanks!

Eigen/src/SVD/BDCSVD.h:350:48: error: too many arguments provided to function-like macro invocation
    Map<MatrixXr> B2(m_workspace.data()+2*n*n, n,  n);
                                               ^
openvdb/util/NodeMasks.h:60:12: note: macro 'B2' defined here
\#   define B2(n)  n,     n+1,     n+1,     n+2
           ^
1 error generated.

**Comment by norouzzadeh** [comment]
Hi @TrevorThomson 

Include Eigen before OpenVDB. This solved the problem for me.

#include <Eigen/Eigen>
#include <openvdb/openvdb.h>

**Comment by TrevorThomson** [comment]
Of course, but I was hoping for a change in the library so as not to burden the user to come up with a work-around...
Thanks!

**Comment by OpenVDB-DevTeam** [comment]
The name conflict should now be resolved.
