### ISSUE TITLE
vdb nodes cause houdini to crash

### ISSUE THREAD

**Issue by MeghaS94** [dreamworksanimation/openvdb#135]
I am trying to compile openVDB4.0 houdini toolkit on houdini 15.5. I have sourced the houdini setup script and managed to compile the library, the unit tests also run. The new openVDB nodes show up in houdini, but when I use the createVDB node, houdini crashes with a memory usage error. I am able to compile and execute the examples in the openVDB cookbook with version 4. The versions of the dependencies I have used are : gnu make 3.81, and cppunit version 1.13, the rest of the libraries are as specified in the houdini HDK.

**Comment by OpenVDB-DevTeam** [comment]
Houdini 15.5 uses the OpenVDB 3 ABI (as does Houdini 16).  If you're using the included makefiles, be sure to build both the OpenVDB library and the Houdini toolkit with the "`abi=3`" option.

**Comment by MeghaS94** [comment]
That worked! Thanks a lot.
