### ISSUE TITLE
OpenVDB example code compilation fails

### ISSUE THREAD

**Issue by MeghaS94** [dreamworksanimation/openvdb#139]
Reference to older issue : #126 
I have installed the vdb 4.0.0 version with abi=3, when I compile the example code, I run into the similar error, undefined reference to openvdb::v4_0_0::math::simplify(std::shared_ptr<openvdb::v4_0_0::math::AffineMap>) .
openvdb::v4_0_0::io::setStreamMetadataPtr(std::ios_base&,std::shared_ptr<openvdb::v4_0_0::io::StreamMetadata>&, bool)
I am not sure how to set the ABI during compilation. Is it a flag that needs to be set during compilation?

**Comment by OpenVDB-DevTeam** [comment]
If the OpenVDB library was compiled with `abi=3`, then when compiling code that depends on the library, define the macro `OPENVDB_3_ABI_COMPATIBLE` (for example, with "`-DOPENVDB_3_ABI_COMPATIBLE`").

**Comment by MeghaS94** [comment]
worked! Thanks

**Comment by Megidd** [comment]
I was receiving the same error:

```
undefined reference to openvdb::v7_1::math::simplify(std::shared_ptr<openvdb::v7_1::math::AffineMap>)
```

Defining `OPENVDB_7_ABI_COMPATIBLE` macro resolved it.
