### ISSUE TITLE
Archives have same UUIDs

### ISSUE THREAD

**Issue by jlefley** [dreamworksanimation/openvdb#146]
I use ```Archive::getUniqueTag()``` to validate the identity of archives in an application and I noticed that under some circumstances different archives can have the same UUID as returned from ```getUniqueTag()```. I looked at the code and it appears that when writing an archive, ```Archive::writeHeader()``` uses the time in seconds since the Unix epoch as the seed to the random number generator used to generate the UUIDs (https://github.com/dreamworksanimation/openvdb/blob/master/openvdb/io/Archive.cc#L978).

I think this causes multiple archives to receive the same UUID if a program writes out the archives within the same second. Perhaps the generator could be seeded only once or a different seed mechanism could be used?

**Comment by OpenVDB-DevTeam** [comment]
This should be fixed with the latest commit (4b74af8).  Please let us know if you still see the problem.
