### ISSUE TITLE
Compiling fails with boost >= 1.65

### ISSUE THREAD

**Issue by thankjura** [dreamworksanimation/openvdb#170]
/var/tmp/portage/media-gfx/openvdb-4.0.2/work/openvdb-4.0.2/openvdb/python/pyFloatGrid.cc: In function ‘void exportFloatGrid()’:
/var/tmp/portage/media-gfx/openvdb-4.0.2/work/openvdb-4.0.2/openvdb/python/pyFloatGrid.cc:50:9: error: ‘py::numeric’ has not been declared
     py::numeric::array::set_module_and_type("numpy", "ndarray");
         ^~~~~~~

python/numeric.hpp removed from boost
https://github.com/boostorg/python/commit/2d1f66fd1948fa28fde05f4c533b13fb3c96d782

**Comment by dokipen3d** [comment]
from the boost 1.65 notes....

> The boost::python::numeric API has been removed, as it is being obsoleted by boost::python::numpy.

**Comment by dracwyrm** [comment]
Will porting boost::python::numeric to boost::python::numpy be compatible with previous versions of boost, or do we need logic to detect which version of boost is being used?

**Comment by OpenVDB-DevTeam** [comment]
boost::python::numpy was added in Boost 1.63, but the VFX reference platform specifies Boost 1.61 through 2018.  So boost::python::numpy support will need to be conditionally compilable.

**Comment by dracwyrm** [comment]
I don't know enough about Boost to write a conditional or what to replace that line with. If someone were to post a bit of code showing what would need to change, I can make a patch for all occurrences. This bug is preventing Gentoo users from upgrading to Boost 1.65.

Thanks.

**Comment by svenstaro** [comment]
Same for Arch Linux. Our boost 1.65.1 rebuild is blocked on this.

**Comment by dracwyrm** [comment]
From what I've been reading, something like this needs to be done:
namespace p = boost::python;
namespace np = boost::python::numpy;
p::list l;
l.append('a');
np::ndarray example_list = np::array (l);

There's ndarray on one side and array on the other.

Can variables be typedef'd like in C++? If so, then if Boost is less than version 1.63, then myNdarray = py::numeric::array and myArray = py::numeric::array. However, if boost is 1.63 or newer then myNdarray = py::numpy::ndarray and myArray = py::numpy::array.
Or could I namespace the whole path? Like: namespace myNdarray = boost::python::numpy::ndarray?

myNdarray would be used on the left hand side of a = and myArray on the right. However, I don't know what to do about a function like this:
const py::numeric::array arrayObj = pyutil::extractArg<py::numeric::array>(
            arrObj, opName[toGrid], pyutil::GridTraits<GridType>::name(),
            /*argIdx=*/1, "numpy.ndarray");
would numpy.ndarray work with both versions of myNdarray?

What do you think?

**Comment by dracwyrm** [comment]
@thankjura @dokipen3d @svenstaro Could you do me a favor and test this patch I made?
https://github.com/dracwyrm/openvdb/commit/22d09714f9a6a29c62668b533495ed2afd4251ef
There must be a simpler way. However, It compiles with Boost 1.65 and passes the test file they have. That is the only thing I used to test as I don't use the python module.

However, I was not able to test it out on Boost versions less than 1.65. It's difficult to downgrade. I will try, but I need people to help test that actually use the module and then I can make a PR, unless a cleaner way is found.

Cheers.

**Comment by svenstaro** [comment]
Patch confirmed working.

**Comment by dracwyrm** [comment]
@svenstaro Were you able to try with Boost 1.63 or 1.64 as well?

Thanks for testing. :)

**Comment by svenstaro** [comment]
Boost 1.64, yes. Compiled fine.

**Comment by thankjura** [comment]
Boost 1.65. Compiled successfully.

**Comment by dokipen3d** [comment]
I can give it a go on osx over the next couple of days. I usually use the houdini libraries as they will match the vfx platform and are known to work. I'll try with the brew boost on osx.

**Comment by dracwyrm** [comment]
@thankjura Maybe I can add this patch temporarily to Gentoo. It seems to work and passes the Test script, even though it's not the prettiest of fixes. It may take a while for a new release. I've been wanting to release 4.0.2 for awhile now, but held up to get a fix for this.

**Comment by thankjura** [comment]
@dracwyrm Ok

**Comment by dracwyrm** [comment]
Attempted fix in PR https://github.com/dreamworksanimation/openvdb/pull/173

**Comment by luomomo** [comment]
> From what I've been reading, something like this needs to be done:
> namespace p = boost::python;
> namespace np = boost::python::numpy;
> p::list l;
> l.append('a');
> np::ndarray example_list = np::array (l);
> 
> There's ndarray on one side and array on the other.
> 
> Can variables be typedef'd like in C++? If so, then if Boost is less than version 1.63, then myNdarray = py::numeric::array and myArray = py::numeric::array. However, if boost is 1.63 or newer then myNdarray = py::numpy::ndarray and myArray = py::numpy::array.
> Or could I namespace the whole path? Like: namespace myNdarray = boost::python::numpy::ndarray?
> 
> myNdarray would be used on the left hand side of a = and myArray on the right. However, I don't know what to do about a function like this:
> const py::numeric::array arrayObj = pyutil::extractArgpy::numeric::array(
> arrObj, opName[toGrid], pyutil::GridTraits::name(),
> /_argIdx=_/1, "numpy.ndarray");
> would numpy.ndarray work with both versions of myNdarray?
> 
> What do you think?

Hi ,I meet the same problem now ,how can I change numeric::array::set_module_and_type to the new boost?

> From what I've been reading, something like this needs to be done:
> namespace p = boost::python;
> namespace np = boost::python::numpy;
> p::list l;
> l.append('a');
> np::ndarray example_list = np::array (l);
> 
> There's ndarray on one side and array on the other.
> 
> Can variables be typedef'd like in C++? If so, then if Boost is less than version 1.63, then myNdarray = py::numeric::array and myArray = py::numeric::array. However, if boost is 1.63 or newer then myNdarray = py::numpy::ndarray and myArray = py::numpy::array.
> Or could I namespace the whole path? Like: namespace myNdarray = boost::python::numpy::ndarray?
> 
> myNdarray would be used on the left hand side of a = and myArray on the right. However, I don't know what to do about a function like this:
> const py::numeric::array arrayObj = pyutil::extractArgpy::numeric::array(
> arrObj, opName[toGrid], pyutil::GridTraits::name(),
> /_argIdx=_/1, "numpy.ndarray");
> would numpy.ndarray work with both versions of myNdarray?
> 
> What do you think?

numeric::array::set_module_and_type("numpy", "ndarray");


> From what I've been reading, something like this needs to be done:
> namespace p = boost::python;
> namespace np = boost::python::numpy;
> p::list l;
> l.append('a');
> np::ndarray example_list = np::array (l);
> 
> There's ndarray on one side and array on the other.
> 
> Can variables be typedef'd like in C++? If so, then if Boost is less than version 1.63, then myNdarray = py::numeric::array and myArray = py::numeric::array. However, if boost is 1.63 or newer then myNdarray = py::numpy::ndarray and myArray = py::numpy::array.
> Or could I namespace the whole path? Like: namespace myNdarray = boost::python::numpy::ndarray?
> 
> myNdarray would be used on the left hand side of a = and myArray on the right. However, I don't know what to do about a function like this:
> const py::numeric::array arrayObj = pyutil::extractArgpy::numeric::array(
> arrObj, opName[toGrid], pyutil::GridTraits::name(),
> /_argIdx=_/1, "numpy.ndarray");
> would numpy.ndarray work with both versions of myNdarray?
> 
> What do you think?
Hi,
Do you mean change  numeric::array to numpy:ndarrray?
  numeric::array-> bn::ndarray
but how  numeric::array::set_module_and_type("numpy", "ndarray") work in 1.65 or higher verion?

**Comment by luomomo** [comment]
> @thankjura @dokipen3d @svenstaro Could you do me a favor and test this patch I made?
> [dracwyrm@22d0971](https://github.com/dracwyrm/openvdb/commit/22d09714f9a6a29c62668b533495ed2afd4251ef)
> There must be a simpler way. However, It compiles with Boost 1.65 and passes the test file they have. That is the only thing I used to test as I don't use the python module.
> 
> However, I was not able to test it out on Boost versions less than 1.65. It's difficult to downgrade. I will try, but I need people to help test that actually use the module and then I can make a PR, unless a cleaner way is found.
> 
> Cheers.

Hi ,I also meet this problem. I don't know how to make py::numeric::array::set_module_and_type("numpy", "ndarray") work in a new boost version. 
Did need to change to bn::ndarray:xxxx()

**Comment by xiaozhang404-coding** [comment]
Do not downgrade the boost version, and only use the hpp header file of boost1.64 after downloading boost1.64. Can this kind of problem be solved?

**Comment by luomomo** [comment]
O(∩_∩)O非常感谢您给我发来邮件，稍后我会仔细阅读。
