### ISSUE TITLE
 release 4.0.2 source code SHA256 and Homebrew install

### ISSUE THREAD

**Issue by dcoeurjo** [dreamworksanimation/openvdb#172]
I'm using openvdb via the Homebrew package manager on MacOs (https://github.com/Homebrew/homebrew-core). Homebrew uses the source code release tarball SHA256 to identify the package and apparently, the SHA has changed on your server of the version 4.0.2 (https://github.com/Homebrew/homebrew-core/pull/17757):

        url "https://github.com/dreamworksanimation/openvdb/archive/v4.0.2.tar.gz"
before 
      
        sha256 "d86852dfff43251a3566f3a25e801591df498a9591558a39f237e935f15e138e"
after 
     
        sha256 "7d995976cf124136b874d006496c37589f32de1b877ee7ccce626710823e8dbb" 

Could you please confirm that the later is the good one ?

Thanks in advance.

**Comment by OpenVDB-DevTeam** [comment]
7d995976cf124136b874d006496c37589f32de1b877ee7ccce626710823e8dbb is the correct hash.  A minor fix to one of the makefiles was made on July 31, a couple of days after the initial 4.0.2 release.

**Comment by dcoeurjo** [comment]
Thanks for the confirmation. I’ll report it to home brew.
