### ISSUE TITLE
Failure to compile: Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by solarismaria** [dreamworksanimation/openvdb#209]
I'm trying to compile openvdb, but I'm running into an issue. This is a version external to Houdini with a yt python installation. This is the error, and it goes on and on for many lines, always preceded with 'boost::python::numpy':

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]
Undefined symbols for architecture x86_64:
  "boost::python::numpy::equivalent(boost::python::numpy::dtype const&, boost::python::numpy::dtype const&)", referenced from:
      pyGrid::arrayTypeId(boost::python::numpy::ndarray const&) in pyFloatGrid.o
      pyGrid::arrayTypeId(boost::python::numpy::ndarray const&) in pyIntGrid.o
      pyGrid::arrayTypeId(boost::python::numpy::ndarray const&) in pyVec3Grid.o 
and more...ending with:
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:873: pyopenvdb.so] Error 1

In the Makefile, I've set my PYTHON_INCL_DIR and PYTHON_LIB_DIR to my local yt-conda version, also using the corresponding NUMPY_INCL_DIR from the yt-conda installation. I'm running macOS 10.12.6, using python 3.6, boost version 1.65.1. 

I'd appreciate any help on what I might be able to do to fix this error. Thanks!

**Comment by OpenVDB-DevTeam** [comment]
Does your libboost_python include numpy symbols?  Some Boost distributions provide separate libboost_python and libboost_numpy libraries.  If that's the case, you'll need to set BOOST_PYTHON_LIB to include both (e.g., "`BOOST_PYTHON_LIB := -lboost_python-mt -lboost_numpy-mt`").

**Comment by solarismaria** [comment]
Ah, thanks! Yes, that was it. Should I be concerned about the warning:

clang: warning: argument unused during compilation: '-pthread' [-Wunused-command-line-argument]

**Comment by OpenVDB-DevTeam** [comment]
No cause for concern.  Some compilers require `-pthread` for both compiling and linking.  Others, like Clang, require it only for compiling.
