### ISSUE TITLE
Possible to add items to a grid in parallel?

### ISSUE THREAD

**Issue by SteveMacenski** [dreamworksanimation/openvdb#218]
Periodically, I'll get a 

```
 /usr/include/openvdb/tree/InternalNode.h:3110: 

 void openvdb::v3_1::tree::InternalNode<_ChildNodeType, Log2Dim>::setChildNode(openvdb::v3_1::Index, openvdb::v3_1::tree::InternalNode<_ChildNodeType, Log2Dim>::ChildNodeType*) [with _ChildNodeType = openvdb::v3_1::tree::InternalNode<openvdb::v3_1::tree::LeafNode<double, 3u>, 4u>; unsigned int Log2Dim = 5u; openvdb::v3_1::Index = unsigned int; 

openvdb::v3_1::tree::InternalNode<_ChildNodeType, Log2Dim>::ChildNodeType = openvdb::v3_1::tree::InternalNode<openvdb::v3_1::tree::LeafNode<double, 3u>, 4u>]: 

Assertion 'mChildMask.isOff(i)' failed.
```

when I do so.

**Comment by OpenVDB-DevTeam** [comment]
In general, it's not safe to add nodes to or remove nodes from a tree in parallel, and it's not safe to toggle the active states of tiles or voxels within a single node in parallel, or to read from a grid while another thread is writing to it.  Those are the main restrictions.

It's usually best, though, to have each thread operate on its own tree (perhaps thread-local) and then to merge those trees to get the final result.  As long as each thread accesses voxels in a reasonably spatially-coherent pattern that doesn't overlap significantly with other threads, the merge operation is very efficient.  There are many examples of this technique, using `tbb::parallel_reduce`, throughout the code.

**Comment by SteveMacenski** [comment]
Thanks for the info, that definitely helps and puts me in the right direction.
