### ISSUE TITLE
openvdb::tools::meshToLevelSet ignores Interrupter for "pure" meshes

### ISSUE THREAD

**Issue by dougepps** [dreamworksanimation/openvdb#236]
openvdb::tools::meshToLevelSet (via doMeshConversion<> ) doesn't pass the Interrupter&  on to meshToVolume<> () when it detects that the mesh is either all quads or all triangles.

Function is @ openvdb/tools/MeshToVolume.h:3412

relevant calls openvdb/tools/MeshToVolume.h:3448, openvdb/tools/MeshToVolume.h:3441
(or thereabouts)

**Comment by OpenVDB-DevTeam** [comment]
This issue is fixed in commit f44e305f.  Thanks for reporting it.
