### ISSUE TITLE
grid name from vdb convert SOP (from houdini volumes) is empty 

### ISSUE THREAD

**Issue by dokipen3d** [dreamworksanimation/openvdb#246]
Hi all

We have some code at work that uses vdbs from houdini which have been converted from houdini volumes using vdbConvert SOP.

A while ago I discovered that the grid name is empty so we can't identify that volume. I looked at the vdb convert SOP and it looks like it calls GU_PrimVDB::convertVolumesToVDBs()  in GU_PrimVDB.cc which itself calls ...

GU_PrimVDB::buildFromPrimVolume(
			dst_geo, *vol, nullptr, flood_sdf, prune, tolerance,
			activate_inside_sdf);

...with nullptr as the third name parameter. 

I'm guessing thats where it should be set (from the houdini prim name?).

Is this a side effects issue or something we can change in this repo? Or am I off base and missing something?

Cheers
Dan

**Comment by OpenVDB-DevTeam** [comment]
Dan, your analysis is correct, and a fix is in the works, but it will require coordination with SideFX.  As an interim workaround for this issue, the Metadata SOP was recently updated (f44e305f8c) with an option to set the name properly.

**Comment by OpenVDB-DevTeam** [comment]
This should be fixed as of Houdini 16.0.1048, 16.5.551 and 17.0.297.
