### ISSUE TITLE
Makefile refers to  "houdini_setup" script which is not included

### ISSUE THREAD

**Issue by sterlingcrispin** [dreamworksanimation/openvdb#45]
where is this script ? 

(Source the houdini_setup script  to set those two environment variables.)

**Comment by wrosecrans** [comment]
It comes with houdini as a part of the installation, and sets up your shell
with all of the houdini related environment variables.

On Sun, Dec 13, 2015 at 12:23 PM, Sterling Crispin <notifications@github.com

**Comment by sterlingcrispin** [comment]
There are many downloads here http://www.openvdb.org/download/ that tell you to source this script, none of them seem to recommend downloading houdini first

**Comment by sterlingcrispin** [comment]
does that come with  the Houdini HDK (ftp://ftp.sidefx.com/public/Houdini12.0) ?  That file is listed as optional but the makefile seems to depend on this

**Comment by emilemold** [comment]
What you were refering to is the houdini shell required for running the installation? open a terminal and cd to your houdini install directory, then type "source houdini_setup" in terminal. Then cd openvdb_houdini directory and make && make install .

**Comment by sterlingcrispin** [comment]
Yes I know, but the make file needs to be updated with this information
because its really misleading

**Comment by OpenVDB-DevTeam** [comment]
This is explained in the INSTALL file.
