### ISSUE TITLE
Building against boost 1.60 causes errors with python module.

### ISSUE THREAD

**Issue by mrxzzy** [dreamworksanimation/openvdb#48]
The grid.deepCopy() call produces this error:

`    c = g.deepCopy()
TypeError: No to_python (by-value) converter found for C++ type: boost::shared_ptr<openvdb::v3_2_0::Grid<openvdb::v3_2_0::tree::Tree<openvdb::v3_2_0::tree::RootNode<openvdb::v3_2_0::tree::InternalNode<openvdb::v3_2_0::tree::InternalNode<openvdb::v3_2_0::tree::LeafNode<float, 3u>, 4u>, 5u> > > > >
`

Demo script:

`
import sys
import pyopenvdb as vdb

g = vdb.FloatGrid()
g.fill(min=(0, 0, 0), max=(100, 100, 100), value=1.0)

c = g.deepCopy()
`

Reverting to boost 1.59 works around this.

In my attempts to sort out where the issue was coming from, I also tried building openvdb 3.1 and 3.0 against boost 1.60 and they fail in the same way. This happens with both python 2 and 3.

**Comment by OpenVDB-DevTeam** [comment]
Commit [2266ecf](https://github.com/dreamworksanimation/openvdb/commit/2266ecf92a77d3bcbb171a63e0c0511d16282022) should resolve this issue.  Thanks for reporting it.
