### ISSUE TITLE
Internal use of Metadata.h or Platform.cc violates style guide on indirect header inclusion.

### ISSUE THREAD

**Issue by MrMormon** [dreamworksanimation/openvdb#52]
This could be an intro refactor exercise for me, but I want to check first. [Metadata.h](https://github.com/dreamworksanimation/openvdb/blob/master/openvdb/Metadata.h) does nothing but expose part of the metadata folder namespace-free for convenience, but it's used internally too. [Platform.cc](https://github.com/dreamworksanimation/openvdb/blob/master/openvdb/Platform.cc) is similar (wherever [Platform.h](https://github.com/dreamworksanimation/openvdb/blob/master/openvdb/Platform.h) is used).

**Comment by MrMormon** [comment]
To clarify, the files don't violate rules, but anything in the codebase that uses them by definition does.

**Comment by OpenVDB-DevTeam** [comment]
Needed for compatibility and to isolate platform dependencies.
