### ISSUE TITLE
openvdb/math/Math.h isApproxZero exclusive, isApproxEqual inclusive

### ISSUE THREAD

**Issue by MrMormon** [dreamworksanimation/openvdb#55]
[Math.h](https://github.com/dreamworksanimation/openvdb/blob/master/openvdb/math/Math.h) I mean inclusive/exclusive in terms of tolerance bounds. Is this intended?

**Comment by OpenVDB-DevTeam** [comment]
Thank you for pointing this out, the current isApproxZero implementation does not work correctly when the tolerance is zero.  The fix will be on GitHub soon.
