### ISSUE TITLE
Is it intended to define OPENVDB_IMPORT as __attribute__((visibility("default")))?

### ISSUE THREAD

**Issue by ongamex** [dreamworksanimation/openvdb#57]
Is it intended to *_ALWAYS *_define OPENVDB_IMPORT as **attribute**((visibility("default"))) under non Windows platforms?

By including almost any openvdb header(openvdb.h is enough). My *.so files start to export all the header file declared/defined symbols. (Example is Maps.h)

**Comment by e4lam** [comment]
Yes, that is intended in particular for use with the gcc command line option, "-fvisibility=hidden". Please see the GCC Wiki on this topic here for more info: https://gcc.gnu.org/wiki/Visibility

The intended effect is that OpenVDB symbols declared with OPENVDB_API will get public visibility and everything else by default will get private visibility.

**Comment by ongamex** [comment]
"-fvisibility=hidden" won't take effect on symbols defined in openvdb headers (example is maps.h) as I include those headers in my translation units.

**Comment by e4lam** [comment]
Is it all the OPENVDB_API symbols in Maps.h being exported from your source? Or just the ones whose definition is also found in that header?

The change to disable the use of the visibility attribute is minimal to Platform.h so if you have some suggestions, we can take it up with the OpenVDB team.

**Comment by ongamex** [comment]
Just the ones whose definition is also found in that header.
Changing the OPENVDB_API did the trick, but I wanted to check if there is an intention here.

**Comment by e4lam** [comment]
If it's only the functions/classes whose definition is also found in that header, then it sounds like maybe those should not have OPENVDB_API in the first place.

**Comment by ongamex** [comment]
Yep, this is basically my question.

**Comment by e4lam** [comment]
I tried but found out that you cannot simply remove OPENVDB_API in a way that avoids this problem and still have things work without lots of work. Take the GridBase class for example which has OPENVDB_API but it has some method implemented inside the library while other methods are implemented in the header. In this case, the methods in the header get exported but not the ones implemented inside the library.

So what combination actually works for you? Are you compiling libopenvdb with OPENVDB_API defined with visibility=default but not when you link against it? Are you compiling with -fvisibility=hidden in both cases?

**Comment by e4lam** [comment]
PS. I don't have time to try but maybe try making `#define OPENVDB_IMPORT` to nothing while leaving the visibility attribute for `OPENVDB_EXPORT`. Recompile both openvdb and your library that uses it. ie. in Platform.h make it

> #ifdef __GNUC__
>     #define OPENVDB_EXPORT __attribute__((visibility("default")))
>     #define OPENVDB_IMPORT
> #endif

**Comment by ongamex** [comment]
Currently I use OpenVDB as it is. I wanted to double check if the definiton of OPENVDB_IMPORT as attribute((visibility("default"))) was intentional or not.

**Comment by e4lam** [comment]
Well, it was intentional because I thought it was necessary from the wiki link I posted. If you find that it's not needed then maybe try submitting pull request.
