### ISSUE TITLE
TestTree.cc uses 'small' as a variable name, 'small' is already defined on Windows

### ISSUE THREAD

**Issue by caron** [dreamworksanimation/openvdb#59]
I don't have a CLA but here is a tip for fixing the unittest for Windows builds...

https://github.com/caron/openvdb/blob/195735f531955119c9c4d57165dbdea3f34070d2/openvdb/unittest/TestTree.cc#L1662-L1680

small is defined in 'rpcndr.h' as...

`#define small char`

**Comment by e4lam** [comment]
Please submit a pull request.

**Comment by caron** [comment]
OK, but I need to learn how to submit a pull request for only a single changeset.

**Comment by e4lam** [comment]
Thank you!

**Comment by caron** [comment]
You're welcome! I personally have more fixes for Windows, some gathered from the community, that I think could also be considered. Right now the library itself builds nicely on Windows, but the viewer and the unittest don't. I am unable to build on Linux so I don't know when or if I break the Linux build. Some CI tool would be great here...ie Travis CI or AppVeyor

**Comment by OpenVDB-DevTeam** [comment]
Thank you for reporting this! We've integrated your fix.
