### ISSUE TITLE
Support for building python module for multiple versions of python in new CMake files

### ISSUE THREAD

**Issue by dracwyrm** [dreamworksanimation/openvdb#78]
I noticed that the new CMake files don't have support for building the python module, unless I missed that.

Anyways, I would like to request that the build system should somehow take a list of all versions to build the python module for, like 2.7, 3.4, 3.5... I use Gentoo where we can have multiple versions installed to support various packages.

This should also mean that auto-finding the python implementations should be overrided since there is a default that /usr/bin/python, /usr/bin/python2, /usr/bin/python3 link to, so I need to set the path to the correct version which our build system does for us.

Thanks,
Jon

**Comment by nyue** [comment]
Python module is now being built and installed pending

https://github.com/dreamworksanimation/openvdb/pull/77

Cheers

**Comment by dracwyrm** [comment]
@nyue Correct me if I'm wrong, but it doesn't look like there is a way to manually select the python binary and library paths???

**Comment by nyue** [comment]
@dracwyrm I am in the process of verifying Python 3.x with OpenVDB, I need to rebuild existing dependency for Python 3.x before I can commence verification. Meanwhile, I do have a situation where I need to specific specific location for Python 2.x and I do so with the following CMAKE variable that the FindPythonLibs module will use. They are PYTHON_EXECUTABLE, PYTHON_LIBRARY and PYTHON_INCLUDE_DIR

NOTE : I assume you will have your Boost Python built with Python 3.x

A concrete example of one of my test environment (CentOS 6.7) build is achieved via the following

export ILMBASE_ROOT=$RHOME/Systems/OpenEXR/v2.2.0
export OPENEXR_ROOT=$RHOME/Systems/OpenEXR/v2.2.0
export BOOST_ROOT=$RHOME/Systems/boost/v1.61.0
export TBB_ROOT=$RHOME/Systems/tbb/tbb44_20150728oss
export GLFW3_ROOT=$RHOME/Systems/glfw/v3.2.1
export BLOSC_ROOT=$RHOME/Systems/c-blosc/v1.7.0
cmake \
	-D PYTHON_LIBRARY=/sw/external/COS6/python/2.6.4/lib/libpython2.6.so \
	-D PYTHON_INCLUDE_DIR=/sw/external/COS6/python/2.6.4/include/python2.6 \
	-D CMAKE_CXX_COMPILER=/sw/external/COS6/gcc/4.8.2/bin/g++ \
	-D CMAKE_C_COMPILER=/sw/external/COS6/gcc/4.8.2/bin/gcc \
	-D CMAKE_CXX_FLAGS=-std=c++11 \
	-D MINIMUM_BOOST_VERSION=1.52 \
	-D ILMBASE_NAMESPACE_VERSIONING=OFF \
	-D OPENEXR_NAMESPACE_VERSIONING=OFF \
	-D USE_GLFW3=ON \
	-D Blosc_USE_STATIC_LIBS=ON \
	-D CMAKE_INSTALL_PREFIX=$RHOME/Systems/OpenVDB/4.0.0 \
	../nyue_openvdb_git

Cheers

**Comment by dracwyrm** [comment]
@nyue If it helps, I have built OpenVDB against python versions 2.7, 3.4, and 3.5. It seems to work. However, I need to use this patch: https://github.com/dreamworksanimation/openvdb/pull/69/files in order to get it to compile with Python 3.x, otherwise it fails. I think this patch should apply to the new v4.0.0 files.

Hope that helps you. :)

**Comment by nyue** [comment]
I can confirm on CentOS 7.0 with Boost 1.62.0 built against Python 3.5.2, running TestOpenVDB.py pass the tests.

So the current CMakeLists.txt as per the pull request is good to go (at least for that environmental combination)

Cheers
