### ISSUE TITLE
VDB Reshape SDF (and others) in world-space units

### ISSUE THREAD

**Issue by jdiversen** [dreamworksanimation/openvdb#9]
Hi there,

We generally find it far more robust and useful to be able to specify distances (like those in Reshape SDF) in units rather than in voxels.  It makes it easier to up-res things in production without having to adjust values in concert with the voxel resolution. Would it be possible to add support for this? 

Thanks,
Jason Iversen

**Comment by OpenVDB-DevTeam** [comment]
resolved
